---
- name: test playbook
  hosts: all
  become: yes
  tasks:
  - name: copy a file
    copy:
     src: /home/ansadmin/index.html
     dest: /home/ansadmin/index.html
     mode: 0600
     owner: soumya
