---
- name: My Test playbook
  hosts: webservers
  become: true
  tasks:
  - name: install httpd package
    yum:
      name: httpd
      state: installed

  - name: service httpd start
    service: 
      name: httpd
      state: started
