---
- name: install httpd
  hosts: webservers
  become: yes
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "Redhat"

  - name: start service httpd
    service:
      name: http---
      state: started
    when: ansible_os_family == "Redhat"
      #ignore_errors: yes

  - name: install httpd
    apt:
      name: httpd
      state: installed
    when: ansible_os_family == "Debian"

  - name: start service httpd
    service:
      name: http
      state: started
    when: ansible_os_family == "Debian"
    

  - name: copy index.html
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html
      mode: 0666
