---
- name: List of users creating
  hosts: all
  become: true
  tasks:
    - name: Create users
      user:
        name: "{{ item }}"
        state: present
      with_items:
        - cone
        - chanu
        - ismail

