---
- name: setup tomcat
  hosts: webservers
  become: true
  tasks:
  - name: install java on Redhat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "Redhat"   

  - name: install java on Debian
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"
 
  - name: Download tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.87/bin/apache-tomcat-8.5.87.tar.gz
      dest: /opt
  
  - name: Extract tar file
    unarchive:
      src: /opt/apache-tomcat-8.5.87.tar.gz
      dest: /opt
      remote_src: yes
   
  - name: Change file permissions(.sh file)
    file:
      path: /opt/apache-tomcat-8.5.87/bin/startup.sh
      mode: 0777


  - name: Executing shell script
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.87/bin/


