---
- name: My Test playbook
  hosts: webservers
  become: true
  tasks:
  - name: stopping  httpd service
    service: 
      name: httpd
      state: stopped

  - name: uninstall httpd service
    yum:
      name: httpd
      state: absent

